namespace Lineage.Core;

/// <summary>
/// Factory methods for common simulation system pipelines.
/// </summary>
public static class SimulationPipelines
{
    public static ISimulationSystem[] CreateMinimalLifeLoop(
        float spatialCellSize = 64f,
        int statsSnapshotIntervalTicks = SimulationScenario.DefaultStatsSnapshotIntervalTicks,
        float bodyRadiusEnergyCostPerSecond = 0f,
        float maxSpeedEnergyCostPerSecond = 0f,
        float turnRateEnergyCostPerSecond = 0f,
        float senseRadiusEnergyCostPerSecond = 0f,
        float visionAngleEnergyCostPerSecond = 0f,
        float eatRateEnergyCostPerSecond = 0f,
        float gutCapacityEnergyCostPerSecond = 0f,
        float digestionRateEnergyCostPerSecond = 0f,
        float biteStrengthEnergyCostPerSecond = 0f,
        float damageResistanceEnergyCostPerSecond = 0f,
        float plantSpecializationEnergyCostPerSecond = 0f,
        float memoryEnergyCostPerSecond = 0f,
        float rtNeatHiddenNodeEnergyCostPerSecond = MetabolismSystem.DefaultRtNeatHiddenNodeEnergyCostPerSecond,
        float rtNeatEnabledConnectionEnergyCostPerSecond = MetabolismSystem.DefaultRtNeatEnabledConnectionEnergyCostPerSecond,
        float eggEnergyCostPerSecond = 0f,
        float eggEnvironmentalDamagePerSecond = 0f,
        float deathMeatCaloriesPerBodyRadius = 4f,
        float deathMeatEnergyFraction = 0.35f,
        float meatDecayCaloriesPerSecond = 0.03f,
        float rottenMeatDamagePerRawKcal = 0f,
        float meatScentRangeMultiplier = 2f,
        float meatScentCaloriesForFullStrength = 60f,
        float meatScentDensitySaturation = 1f,
        bool enableSmallPrey = false,
        float smallPreyPerMillionArea = 0f,
        float smallPreyMaxSpawnsPerSecond = 1f,
        float smallPreyRadius = 2f,
        float smallPreyCalories = 16f,
        float smallPreyHealth = 0.18f,
        float smallPreyMaxSpeed = 7f,
        float smallPreyWanderIntervalSecondsMin = 0.6f,
        float smallPreyWanderIntervalSecondsMax = 2.2f,
        BiomePressureProfile? smallPreySpawnWeightProfile = null,
        float biteDamagePerSecond = 0.25f,
        float biteEnergyCostPerSecond = 0.12f,
        float biteRangePadding = 1f,
        bool enableCreatureCollision = true,
        float creatureCollisionSafeImpactSpeed = CreatureCollisionSystem.DefaultSafeImpactSpeed,
        float creatureCollisionDamageScale = CreatureCollisionSystem.DefaultDamageScale,
        int creatureCollisionSeparationIterations = CreatureCollisionSystem.DefaultSeparationIterations,
        bool enableInjuryMemory = true,
        float injuryMemoryHalfLifeSeconds = InjuryMemorySystem.DefaultHalfLifeSeconds,
        float injuryMemoryDamageSignalScale = InjuryMemorySystem.DefaultDamageSignalScale,
        bool relocateDepletedResources = true,
        float resourceClusterStrength = 0f,
        float resourceClusterRadius = 180f,
        float plantLocalDispersalChance = 0f,
        float plantLocalDispersalRadius = 220f,
        float plantRespawnDelaySecondsMin = 0f,
        float plantRespawnDelaySecondsMax = 0f,
        float plantRespawnCaloriesMin = 0f,
        float plantRespawnCaloriesMax = 0f,
        bool enableSeasons = false,
        float seasonLengthSeconds = 900f,
        float seasonFertilityAmplitude = 0.3f,
        float seasonPhaseOffsetSeconds = 0f,
        SeasonPhaseMode seasonPhaseMode = SeasonPhaseMode.Global,
        BiomePressureProfile? biomeMovementCostProfile = null,
        BiomePressureProfile? biomeBasalCostProfile = null,
        float thermalMismatchBasalCostMultiplier = 0f,
        BiomePressureProfile? biomeSpeedProfile = null,
        float movementSpeedCostExponent = 1f,
        bool requireReproductionIntent = true,
        float reproductivePrimeAgeSeconds = 240f,
        float reproductiveSenescenceAgeSeconds = 900f,
        float senescentFertilityMultiplier = 0.18f,
        float crowdingFertilityPenalty = 0.65f,
        BiomePressureProfile? biomeSeasonalAmplitudeProfile = null,
        bool enableExtinctPayloadPruning = false,
        int extinctPayloadPruneIntervalTicks = 1_000,
        float mutationStrength = 0.06f,
        float traitMutationRate = 0.2f,
        float brainMutationRate = 0.08f,
        float fatDepositEnergyRatio = FatStorageSystem.DefaultDepositEnergyRatio,
        float fatWithdrawEnergyRatio = FatStorageSystem.DefaultWithdrawEnergyRatio,
        float fatTransferCapacitySharePerSecond = FatStorageSystem.DefaultTransferCapacitySharePerSecond,
        float healingDelaySeconds = CreatureHealingSystem.DefaultHealingDelaySeconds,
        float healingHealthFractionPerSecond = CreatureHealingSystem.DefaultHealingHealthFractionPerSecond,
        float healingEnergyCostPerHealth = CreatureHealingSystem.DefaultHealingEnergyCostPerHealth,
        float healingMinimumEnergy = CreatureHealingSystem.DefaultHealingMinimumEnergy)
    {
        var spatialIndex = new UniformSpatialIndex(spatialCellSize);

        return
        [
            new ResourceRegrowthSystem(
                relocateDepletedResources,
                resourceClusterStrength,
                resourceClusterRadius,
                plantLocalDispersalChance,
                plantLocalDispersalRadius,
                plantRespawnDelaySecondsMin,
                plantRespawnDelaySecondsMax,
                plantRespawnCaloriesMin,
                plantRespawnCaloriesMax,
                enableSeasons,
                seasonLengthSeconds,
                seasonFertilityAmplitude,
                seasonPhaseOffsetSeconds,
                seasonPhaseMode,
                biomeSeasonalAmplitudeProfile),
            new SmallPreySystem(
                enableSmallPrey,
                smallPreyPerMillionArea,
                smallPreyMaxSpawnsPerSecond,
                smallPreyRadius,
                smallPreyCalories,
                smallPreyHealth,
                smallPreyMaxSpeed,
                smallPreyWanderIntervalSecondsMin,
                smallPreyWanderIntervalSecondsMax,
                smallPreySpawnWeightProfile),
            new MetabolismSystem(
                bodyRadiusEnergyCostPerSecond,
                maxSpeedEnergyCostPerSecond,
                turnRateEnergyCostPerSecond,
                senseRadiusEnergyCostPerSecond,
                visionAngleEnergyCostPerSecond,
                eatRateEnergyCostPerSecond,
                gutCapacityEnergyCostPerSecond,
                digestionRateEnergyCostPerSecond,
                biteStrengthEnergyCostPerSecond,
                damageResistanceEnergyCostPerSecond,
                plantSpecializationEnergyCostPerSecond,
                memoryEnergyCostPerSecond,
                rtNeatHiddenNodeEnergyCostPerSecond,
                rtNeatEnabledConnectionEnergyCostPerSecond,
                biomeBasalCostProfile,
                thermalMismatchBasalCostMultiplier),
            new SpatialIndexRebuildSystem(spatialIndex),
            new SimpleForagingSystem(spatialIndex),
            new SmallPreyInteractionSystem(
                spatialIndex,
                biteDamagePerSecond,
                biteEnergyCostPerSecond,
                biteRangePadding,
                CreatureGrabSystem.DefaultHoldRangePadding,
                meatDecayCaloriesPerSecond),
            new MovementSystem(
                biomeMovementCostProfile,
                biomeSpeedProfile,
                movementSpeedCostExponent),
            new CreatureCollisionSystem(
                enableCreatureCollision,
                creatureCollisionSafeImpactSpeed,
                creatureCollisionDamageScale,
                creatureCollisionSeparationIterations),
            new CreatureSpatialIndexRebuildSystem(spatialIndex),
            new EatingSystem(spatialIndex),
            new DigestionSystem(rottenMeatDamagePerRawKcal),
            new InjuryMemorySystem(
                enableInjuryMemory,
                injuryMemoryHalfLifeSeconds,
                injuryMemoryDamageSignalScale),
            new ReproductionSystem(
                requireReproductionIntent: requireReproductionIntent,
                mutationPolicy: WorldMutationPolicy.Uniform(
                    mutationStrength,
                    traitMutationRate,
                    brainMutationRate),
                reproductivePrimeAgeSeconds: reproductivePrimeAgeSeconds,
                reproductiveSenescenceAgeSeconds: reproductiveSenescenceAgeSeconds,
                senescentFertilityMultiplier: senescentFertilityMultiplier,
                crowdingFertilityPenalty: crowdingFertilityPenalty),
            new EggEnvironmentalDamageSystem(eggEnvironmentalDamagePerSecond),
            new EggSystem(eggEnergyCostPerSecond),
            new FatStorageSystem(
                fatDepositEnergyRatio,
                fatWithdrawEnergyRatio,
                fatTransferCapacitySharePerSecond),
            new CreatureHealingSystem(
                healingDelaySeconds,
                healingHealthFractionPerSecond,
                healingEnergyCostPerHealth,
                healingMinimumEnergy),
            new LineageTelemetrySystem(),
            new DeathSystem(deathMeatCaloriesPerBodyRadius, deathMeatEnergyFraction, meatDecayCaloriesPerSecond),
            .. CreateExtinctPayloadPruningSystems(enableExtinctPayloadPruning, extinctPayloadPruneIntervalTicks),
            new StatsRecordingSystem(
                statsSnapshotIntervalTicks,
                biomeMovementCostProfile,
                biomeBasalCostProfile,
                biomeSpeedProfile,
                enableSeasons,
                seasonLengthSeconds,
                seasonFertilityAmplitude,
                seasonPhaseOffsetSeconds,
                seasonPhaseMode,
                thermalMismatchBasalCostMultiplier)
        ];
    }

    public static ISimulationSystem[] CreateNeuralLifeLoop(
        float spatialCellSize = 64f,
        int statsSnapshotIntervalTicks = SimulationScenario.DefaultStatsSnapshotIntervalTicks,
        float bodyRadiusEnergyCostPerSecond = 0f,
        float maxSpeedEnergyCostPerSecond = 0f,
        float turnRateEnergyCostPerSecond = 0f,
        float senseRadiusEnergyCostPerSecond = 0f,
        float visionAngleEnergyCostPerSecond = 0f,
        float eatRateEnergyCostPerSecond = 0f,
        float gutCapacityEnergyCostPerSecond = 0f,
        float digestionRateEnergyCostPerSecond = 0f,
        float biteStrengthEnergyCostPerSecond = 0f,
        float damageResistanceEnergyCostPerSecond = 0f,
        float plantSpecializationEnergyCostPerSecond = 0f,
        float memoryEnergyCostPerSecond = 0f,
        float rtNeatHiddenNodeEnergyCostPerSecond = MetabolismSystem.DefaultRtNeatHiddenNodeEnergyCostPerSecond,
        float rtNeatEnabledConnectionEnergyCostPerSecond = MetabolismSystem.DefaultRtNeatEnabledConnectionEnergyCostPerSecond,
        float memoryDecayPerSecond = NeuralControllerSystem.DefaultMemoryDecayPerSecond,
        float memoryWriteRatePerSecond = NeuralControllerSystem.DefaultMemoryWriteRatePerSecond,
        float eggEnergyCostPerSecond = 0f,
        float eggEnvironmentalDamagePerSecond = 0f,
        float deathMeatCaloriesPerBodyRadius = 4f,
        float deathMeatEnergyFraction = 0.35f,
        float meatDecayCaloriesPerSecond = 0.03f,
        float rottenMeatDamagePerRawKcal = 0f,
        float meatScentRangeMultiplier = 2f,
        float meatScentCaloriesForFullStrength = 60f,
        float meatScentDensitySaturation = 1f,
        bool enableSmallPrey = false,
        float smallPreyPerMillionArea = 0f,
        float smallPreyMaxSpawnsPerSecond = 1f,
        float smallPreyRadius = 2f,
        float smallPreyCalories = 16f,
        float smallPreyHealth = 0.18f,
        float smallPreyMaxSpeed = 7f,
        float smallPreyWanderIntervalSecondsMin = 0.6f,
        float smallPreyWanderIntervalSecondsMax = 2.2f,
        BiomePressureProfile? smallPreySpawnWeightProfile = null,
        float soundRangeMultiplier = CreatureSensingSystem.DefaultSoundRangeMultiplier,
        float soundDensitySaturation = CreatureSensingSystem.DefaultSoundDensitySaturation,
        int worldSenseIntervalTicks = CreatureSensingSystem.DefaultWorldSenseIntervalTicks,
        float closeSenseRefreshProximity = CreatureSensingSystem.DefaultCloseSenseRefreshProximity,
        int closeSenseRefreshMinimumTicks = CreatureSensingSystem.DefaultCloseSenseRefreshMinimumTicks,
        bool enableSectorVision = CreatureSensingSystem.DefaultEnableSectorVision,
        float plantPayoffTraceHalfLifeSeconds = CreatureSensingSystem.DefaultPlantPayoffTraceHalfLifeSeconds,
        int sensingThreadCount = CreatureSensingSystem.DefaultSensingThreadCount,
        bool reuseNeuralActionsOnSkippedWorldSenses = false,
        int neuralControllerThreadCount = NeuralControllerSystem.DefaultNeuralControllerThreadCount,
        float biteDamagePerSecond = 0.25f,
        float biteEnergyCostPerSecond = 0.12f,
        float biteRangePadding = 1f,
        bool enableCreatureCollision = true,
        float creatureCollisionSafeImpactSpeed = CreatureCollisionSystem.DefaultSafeImpactSpeed,
        float creatureCollisionDamageScale = CreatureCollisionSystem.DefaultDamageScale,
        int creatureCollisionSeparationIterations = CreatureCollisionSystem.DefaultSeparationIterations,
        bool enableInjuryMemory = true,
        float injuryMemoryHalfLifeSeconds = InjuryMemorySystem.DefaultHalfLifeSeconds,
        float injuryMemoryDamageSignalScale = InjuryMemorySystem.DefaultDamageSignalScale,
        bool relocateDepletedResources = true,
        float resourceClusterStrength = 0f,
        float resourceClusterRadius = 180f,
        float plantLocalDispersalChance = 0f,
        float plantLocalDispersalRadius = 220f,
        float plantRespawnDelaySecondsMin = 0f,
        float plantRespawnDelaySecondsMax = 0f,
        float plantRespawnCaloriesMin = 0f,
        float plantRespawnCaloriesMax = 0f,
        bool enableSeasons = false,
        float seasonLengthSeconds = 900f,
        float seasonFertilityAmplitude = 0.3f,
        float seasonPhaseOffsetSeconds = 0f,
        SeasonPhaseMode seasonPhaseMode = SeasonPhaseMode.Global,
        BiomePressureProfile? biomeMovementCostProfile = null,
        BiomePressureProfile? biomeBasalCostProfile = null,
        float thermalMismatchBasalCostMultiplier = 0f,
        BiomePressureProfile? biomeSpeedProfile = null,
        BiomePressureProfile? biomeVisionRangeProfile = null,
        float movementSpeedCostExponent = 1f,
        bool requireReproductionIntent = true,
        float reproductivePrimeAgeSeconds = 240f,
        float reproductiveSenescenceAgeSeconds = 900f,
        float senescentFertilityMultiplier = 0.18f,
        float crowdingFertilityPenalty = 0.65f,
        BiomePressureProfile? biomeSeasonalAmplitudeProfile = null,
        bool enableExtinctPayloadPruning = false,
        int extinctPayloadPruneIntervalTicks = 1_000,
        float mutationStrength = 0.06f,
        float traitMutationRate = 0.2f,
        float brainMutationRate = 0.08f,
        float fatDepositEnergyRatio = FatStorageSystem.DefaultDepositEnergyRatio,
        float fatWithdrawEnergyRatio = FatStorageSystem.DefaultWithdrawEnergyRatio,
        float fatTransferCapacitySharePerSecond = FatStorageSystem.DefaultTransferCapacitySharePerSecond,
        float healingDelaySeconds = CreatureHealingSystem.DefaultHealingDelaySeconds,
        float healingHealthFractionPerSecond = CreatureHealingSystem.DefaultHealingHealthFractionPerSecond,
        float healingEnergyCostPerHealth = CreatureHealingSystem.DefaultHealingEnergyCostPerHealth,
        float healingMinimumEnergy = CreatureHealingSystem.DefaultHealingMinimumEnergy)
    {
        var spatialIndex = new UniformSpatialIndex(spatialCellSize);

        return
        [
            new ResourceRegrowthSystem(
                relocateDepletedResources,
                resourceClusterStrength,
                resourceClusterRadius,
                plantLocalDispersalChance,
                plantLocalDispersalRadius,
                plantRespawnDelaySecondsMin,
                plantRespawnDelaySecondsMax,
                plantRespawnCaloriesMin,
                plantRespawnCaloriesMax,
                enableSeasons,
                seasonLengthSeconds,
                seasonFertilityAmplitude,
                seasonPhaseOffsetSeconds,
                seasonPhaseMode,
                biomeSeasonalAmplitudeProfile),
            new SmallPreySystem(
                enableSmallPrey,
                smallPreyPerMillionArea,
                smallPreyMaxSpawnsPerSecond,
                smallPreyRadius,
                smallPreyCalories,
                smallPreyHealth,
                smallPreyMaxSpeed,
                smallPreyWanderIntervalSecondsMin,
                smallPreyWanderIntervalSecondsMax,
                smallPreySpawnWeightProfile),
            new MetabolismSystem(
                bodyRadiusEnergyCostPerSecond,
                maxSpeedEnergyCostPerSecond,
                turnRateEnergyCostPerSecond,
                senseRadiusEnergyCostPerSecond,
                visionAngleEnergyCostPerSecond,
                eatRateEnergyCostPerSecond,
                gutCapacityEnergyCostPerSecond,
                digestionRateEnergyCostPerSecond,
                biteStrengthEnergyCostPerSecond,
                damageResistanceEnergyCostPerSecond,
                plantSpecializationEnergyCostPerSecond,
                memoryEnergyCostPerSecond,
                rtNeatHiddenNodeEnergyCostPerSecond,
                rtNeatEnabledConnectionEnergyCostPerSecond,
                biomeBasalCostProfile,
                thermalMismatchBasalCostMultiplier),
            new SpatialIndexRebuildSystem(spatialIndex),
            new CreatureSensingSystem(
                spatialIndex,
                meatScentRangeMultiplier: meatScentRangeMultiplier,
                meatScentCaloriesForFullStrength: meatScentCaloriesForFullStrength,
                meatScentDensitySaturation: meatScentDensitySaturation,
                biomeSpeedProfile: biomeSpeedProfile,
                biomeVisionRangeProfile: biomeVisionRangeProfile,
                worldSenseIntervalTicks: worldSenseIntervalTicks,
                closeSenseRefreshProximity: closeSenseRefreshProximity,
                closeSenseRefreshMinimumTicks: closeSenseRefreshMinimumTicks,
                enableSectorVision: enableSectorVision,
                plantPayoffTraceHalfLifeSeconds: plantPayoffTraceHalfLifeSeconds,
                sensingThreadCount: sensingThreadCount,
                soundRangeMultiplier: soundRangeMultiplier,
                soundDensitySaturation: soundDensitySaturation),
            new NeuralControllerSystem(
                memoryDecayPerSecond: memoryDecayPerSecond,
                memoryWriteRatePerSecond: memoryWriteRatePerSecond,
                reuseActionsOnSkippedWorldSenses: reuseNeuralActionsOnSkippedWorldSenses,
                neuralControllerThreadCount: neuralControllerThreadCount),
            new CreatureGrabSystem(),
            new MovementSystem(
                biomeMovementCostProfile,
                biomeSpeedProfile,
                movementSpeedCostExponent),
            new CreatureCollisionSystem(
                enableCreatureCollision,
                creatureCollisionSafeImpactSpeed,
                creatureCollisionDamageScale,
                creatureCollisionSeparationIterations),
            new CreatureSpatialIndexRebuildSystem(spatialIndex),
            new EatingSystem(spatialIndex, requireEatIntent: true),
            new DigestionSystem(rottenMeatDamagePerRawKcal),
            new ReproductionSystem(
                requireReproductionIntent: requireReproductionIntent,
                mutationPolicy: WorldMutationPolicy.Uniform(
                    mutationStrength,
                    traitMutationRate,
                    brainMutationRate),
                reproductivePrimeAgeSeconds: reproductivePrimeAgeSeconds,
                reproductiveSenescenceAgeSeconds: reproductiveSenescenceAgeSeconds,
                senescentFertilityMultiplier: senescentFertilityMultiplier,
                crowdingFertilityPenalty: crowdingFertilityPenalty),
            new EggEnvironmentalDamageSystem(eggEnvironmentalDamagePerSecond),
            new EggSystem(eggEnergyCostPerSecond),
            new CreatureAttackSystem(
                spatialIndex,
                biteDamagePerSecond,
                biteEnergyCostPerSecond,
                biteRangePadding,
                requireAttackIntent: true),
            new SmallPreyInteractionSystem(
                spatialIndex,
                biteDamagePerSecond,
                biteEnergyCostPerSecond,
                biteRangePadding,
                CreatureGrabSystem.DefaultHoldRangePadding,
                meatDecayCaloriesPerSecond),
            new InjuryMemorySystem(
                enableInjuryMemory,
                injuryMemoryHalfLifeSeconds,
                injuryMemoryDamageSignalScale),
            new FatStorageSystem(
                fatDepositEnergyRatio,
                fatWithdrawEnergyRatio,
                fatTransferCapacitySharePerSecond),
            new CreatureHealingSystem(
                healingDelaySeconds,
                healingHealthFractionPerSecond,
                healingEnergyCostPerHealth,
                healingMinimumEnergy),
            new LineageTelemetrySystem(),
            new DeathSystem(deathMeatCaloriesPerBodyRadius, deathMeatEnergyFraction, meatDecayCaloriesPerSecond),
            .. CreateExtinctPayloadPruningSystems(enableExtinctPayloadPruning, extinctPayloadPruneIntervalTicks),
            new StatsRecordingSystem(
                statsSnapshotIntervalTicks,
                biomeMovementCostProfile,
                biomeBasalCostProfile,
                biomeSpeedProfile,
                enableSeasons,
                seasonLengthSeconds,
                seasonFertilityAmplitude,
                seasonPhaseOffsetSeconds,
                seasonPhaseMode,
                thermalMismatchBasalCostMultiplier)
        ];
    }

    private static ISimulationSystem[] CreateExtinctPayloadPruningSystems(
        bool enabled,
        int intervalTicks)
    {
        return enabled
            ? [new ExtinctPayloadPruningSystem(intervalTicks)]
            : [];
    }
}
